-- INSERT INTO users(user_name,password) VALUES('Ada Lovelace', 'Smart');
-- INSERT INTO users(user_name,password) VALUES('Bobo', 'Tonto');
-- INSERT INTO users(user_name,password) VALUES('Donkey', 'SS');